deps:
  model:
    encoder_path: models/uc3m_model/encoding
    model_path: models/uc3m_model
outs:
  env_path_name: output_path
  output_folder: inference
params:
  binary_feats:
  - schedule_L1
  - srcip_exists
  - dstip_exists
  - srcip_public
  - dstip_public
  binary_type: PlusMinusOne
  bincat_dict:
    schedule_L1: 24x7
  nlp_feats:
  - - titulo_investigacion
    - use_case_name
    - url_str
    - id_str
  - - extra_data_str
    - action_str
    - fuente
  - - alert_name
  numeric_feats:
  - AlertLevel
  ohe_feats:
  - proyecto_hicks
  - proyecto_kennedy
  - proyecto_magenta
  - proyecto_bali
  - proyecto_cian
  - proyecto_hohens
  - proyecto_jacoblemaire
  - proyecto_wendycalvin
  - proyecto_hoffmann
  - proyecto_galeotti
  - proyecto_harish
  - proyecto_crabeels
  - proyecto_kring
  - proyecto_magenta_publico
  - proyecto_pecs
  - proyecto_masami
  - proyecto_astropolis
  - proyecto_presque
  - proyecto_potomac
  - proyecto_s12mp-opmaev
  - severidad_medium
  - severidad_critical
  - severidad_high
  - srccountry_
  - srccountry_kenya
  - srccountry_united states
  - srccountry_austria
  - srccountry_germany
  - srccountry_portugal
  - srccountry_egypt
  - srccountry_sweden
  - srccountry_turkey
  - srccountry_india
  - srccountry_oman
  - srccountry_mexico
  - srccountry_guatemala
  - srccountry_hong kong
  - srccountry_spain
  - srccountry_france
  - srccountry_netherlands
  - srccountry_ireland
  - srccountry_algeria
  - srccountry_canada
  - srccountry_poland
  - srccountry_japan
  - srccountry_united kingdom
  - srccountry_romania
  - srccountry_singapore
  - srccountry_brazil
  - srccountry_south africa
  - srccountry_moldova, republic of
  - srccountry_china
  - srccountry_taiwan
  - srccountry_indonesia
  - srccountry_australia
  - srccountry_malaysia
  - srccountry_korea
  - srccountry_thailand
  - srccountry_luxembourg
  - srccountry_belgium
  - srccountry_latvia
  - srccountry_denmark
  - srccountry_cambodia
  - srccountry_argentina
  - srccountry_switzerland
  - srccountry_bulgaria
  - srccountry_finland
  - srccountry_russian federation
  - srccountry_bahrain
  - srccountry_greece
  - srccountry_italy
  - srccountry_lithuania
  - srccountry_mauritania
  - srccountry_morocco
  - srccountry_vietnam
  - srccountry_albania
  - srccountry_czech republic
  - dstcountry_
  - dstcountry_spain
  - dstcountry_united states
  - dstcountry_india
  - dstcountry_poland
  - dstcountry_singapore
  - dstcountry_bosnia and herzegovina
  - dstcountry_germany
  - dstcountry_france
  - dstcountry_ireland
  - dstcountry_portugal
  - dstcountry_russian federation
  - dstcountry_ukraine
  - dstcountry_turkey
  - dstcountry_japan
  - dstcountry_netherlands
  - dstcountry_canada
  - dstcountry_sweden
  - dstcountry_hong kong
  - dstcountry_united kingdom
  - dstcountry_argentina
  - dstcountry_china
  - dstcountry_denmark
  - dstcountry_czech republic
  - dstcountry_norway
  - dstcountry_bulgaria
  - dstcountry_finland
  - dstcountry_iceland
  - dstcountry_australia
  - dstcountry_brazil
  - dstcountry_philippines
  - dstcountry_belgium
  - dstcountry_korea
  - dstcountry_lithuania
  - dstcountry_slovakia
  - dstcountry_austria
  - dstcountry_mexico
  - dstcountry_taiwan
  - dstcountry_chile
  - dstcountry_hungary
  - dstcountry_italy
  - dstcountry_malaysia
  - dstcountry_senegal
  - dstcountry_romania
  - dstcountry_colombia
  - dstcountry_luxembourg
  - user_str_
  - user_str_root
  - user_str_admin
  - user_str_guest
  - user_str_default
  - user_str_support
  - user_str_user
  - protocol_str_
  - protocol_str_tcp
  - protocol_str_http
  - protocol_str_udp
  - protocol_str_icmp
  - protocol_str_get
  - protocol_str_head
  - protocol_str_poll
  - protocol_str_patch
  - protocol_str_pfsync
  - protocol_str_proppatch
  - protocol_str_testzzz
  - protocol_str_x-ms-enumatts
  - protocol_str_rpc_out_data
  - protocol_str_search
  - protocol_str_orderpatch
  - protocol_str_acl
  - status_str_
  - status_str_secret - heartbeatfailure
  - status_str_unsafe
  - status_str_defense
  - status_str_vulnerability
  - status_str_quarantined
  - status_str_url
  - status_str_malware
  - status_str_system log
  - status_str_execution
  - status_str_cleared
  - status_str_discovery
  - status_str_role - assignuserorgroup
  - status_str_user - addedtogroup
  - status_str_lateral
  - status_str_abnormal
  - status_str_command
  - status_str_privilege
  - status_str_spyware
  - status_str_initial
  - status_str_wildfire
  - status_str_scan
  - status_str_virus
  - status_str_user - lockout
  - status_str_impact
  - status_str_persistence
  - status_str_user - loginfailure
  - status_str_unscored
  - status_str_credential
  - status_str_exploit
  - status_str_file
  - use_case_id_gmv_gl00005
  - use_case_id_ken_gl00126
  - use_case_id_gmv_gl00066
  - use_case_id_gmv_gl00108
  - use_case_id_ken_gl00029
  - use_case_id_gmv_gl00119
  - use_case_id_gmv_gl00064
  - use_case_id_gmv_gl00081
  - use_case_id_gmv_gl00017
  - use_case_id_gmv_gl00165
  - use_case_id_gmv_gl00270
  - use_case_id_gmv_gl00062
  - use_case_id_gmv_gl00003
  - use_case_id_gmv_gl00209
  - use_case_id_gmv_gl00115
  - use_case_id_gmv_gl00092
  - use_case_id_gmv_gl00214
  - use_case_id_ken_gl00028
  - use_case_id_gmv_gl00120
  - use_case_id_gmv_gl00004
  - use_case_id_gmv_gl00054
  - use_case_id_gmv_gl00033
  - use_case_id_gmv_gl00210
  - use_case_id_gmv_gl00008
  - use_case_id_gmv_gl00057
  - use_case_id_gmv_gl00290
  - use_case_id_gmv_gl00197
  - use_case_id_gmv_gl00118
  - use_case_id_gmv_gl00019
  - use_case_id_gmv_gl00168
  - use_case_id_gmv_gl00117
  - use_case_id_gmv_gl00277
  - use_case_id_gmv_gl00114
  - use_case_id_gmv_gl00018
  - use_case_id_gmv_gl00043
  - use_case_id_gmv_gl00058
  - use_case_id_gmv_gl00167
  - use_case_id_cia_sp00005
  - use_case_id_gmv_gl00109
  - use_case_id_gmv_gl00024
  - use_case_id_gmv_gl00123
  - use_case_id_gmv_gl00272
  - use_case_id_gmv_gl00225
  - use_case_id_gmv_gl00001
  - use_case_id_gmv_gl00028
  - use_case_id_gmv_gl00061
  - use_case_id_gmv_gl00221
  - use_case_id_gmv_gl00219
  - use_case_id_cia_sp00004
  - use_case_id_cia_sp00014
  - use_case_id_gmv_gl00220
  - use_case_id_gmv_gl00037
  - use_case_id_gmv_gl00060
  - use_case_id_gmv_gl00035
  - use_case_id_cia_sp00008
  - use_case_id_gmv_gl00122
  - use_case_id_gmv_gl00036
  - use_case_id_gmv_gl00267
  - use_case_id_gmv_gl00125
  - use_case_id_cia_sp00002
  - use_case_id_gmv_gl00285
  - use_case_id_gmv_gl00074
  - use_case_id_gmv_gl00073
  - use_case_id_gmv_gl00075
  - use_case_id_gmv_gl00013
  - use_case_id_gmv_gl00029
  - use_case_id_gmv_gl00096
  - use_case_id_gmv_gl00111
  - use_case_id_gmv_gl00136
  - use_case_id_gmv_gl00179
  - use_case_id_gmv_gl00031
  - use_case_id_gmv_gl00044
  - use_case_id_gmv_gl00212
  - use_case_id_gmv_gl00213
  - use_case_id_wen_sp00001
  - use_case_id_gmv_gl00222
  - use_case_id_gmv_gl00041
  - use_case_id_gmv_gl00289
  - use_case_id_gmv_gl00135
  - use_case_id_gmv_gl00105
  - use_case_id_gmv_gl00287
  - use_case_id_gmv_gl00145
  - use_case_id_gmv_gl00016
  - use_case_id_gmv_gl00055
  - use_case_id_gmv_gl00199
  - use_case_id_gmv_gl00193
  - use_case_id_gmv_gl00080
  - use_case_id_gmv_gl00067
  - use_case_id_gmv_gl00072
  - use_case_id_kri_gl00224
  - use_case_id_cia_sp00003
  - use_case_id_gmv_gl00039
  - use_case_id_gmv_gl00046
  - use_case_id_gmv_gl00129
  - use_case_id_cia_sp00013
  - use_case_id_gmv_gl00012
  - use_case_id_gmv_gl00030
  - use_case_id_gmv_gl00110
  - use_case_id_gmv_gl00198
  - use_case_id_gmv_gl00065
  - use_case_id_gmv_gl00130
  - use_case_id_gmv_gl00126
  - use_case_id_gmv_gl00186
  - use_case_id_gmv_gl00187
  - use_case_id_gmv_gl00112
  - use_case_id_gmv_gl00271
  - use_case_id_gmv_gl00146
  - use_case_id_mag_sp00001
  - use_case_id_gmv_gl00127
  - use_case_id_gmv_gl00124
  - use_case_id_gmv_gl00042
  - use_case_id_gmv_gl00097
  - use_case_id_cia_sp00001
  - use_case_id_gmv_gl00086
  - use_case_id_gmv_gl00100
  - use_case_id_gmv_gl00027
  - use_case_id_gmv_gl00286
  - use_case_id_gmv_gl00021
  - use_case_id_gmv_gl00015
  - use_case_id_gmv_gl00098
  - use_case_id_gmv_gl00265
  - use_case_id_gmv_gl00164
  - use_case_id_gmv_gl00077
  - use_case_id_gmv_gl00094
  - use_case_id_gmv_gl00173
  - use_case_id_gmv_gl00104
  - use_case_id_gmv_gl00137
  - use_case_id_gmv_gl00082
  - use_case_id_gmv_gl00194
  - use_case_id_cia_sp00006
  - use_case_id_gmv_gl00045
  - use_case_id_gmv_gl00078
  - use_case_id_gmv_gl00310
  - use_case_id_gmv_gl00047
  - use_case_id_gmv_gl00273
  - use_case_id_gmv_gl00305
  - use_case_id_gmv_gl00079
  - use_case_id_gmv_gl00053
  - use_case_id_gmv_gl00153
  - use_case_id_cra_sp00003
  - use_case_id_cra_sp00008
  - use_case_id_hoh_sp00007
  - use_case_id_gmv_gl00084
  - use_case_id_gmv_gl00010
  - use_case_id_gmv_gl00311
  - use_case_id_cra_sp00013
  - use_case_id_cra_sp00002
  - use_case_id_gmv_gl00190
  - use_case_id_gmv_gl00090
  - use_case_id_hoh_sp00008
  - use_case_id_gmv_gl00319
  - use_case_id_gmv_gl00002
  - use_case_id_hoh_sp00003
  - use_case_id_gmv_gl00107
  - use_case_id_uya_sp00012
  - use_case_id_gmv_gl00085
  - use_case_id_gmv_gl00009
  - use_case_id_gmv_gl00196
  - use_case_id_gmv_gl00063
  - use_case_id_gmv_gl00229
  - use_case_id_gmv_gl00218
  - use_case_id_hoh_sp00002
  - use_case_id_gmv_gl00317
  - use_case_id_cra_sp00011
  - use_case_id_uya_sp00016
  - use_case_id_gmv_gl00143
  - use_case_id_gmv_gl00302
  - use_case_id_gmv_gl00321
  - use_case_id_gmv_gl00326
  - use_case_id_gmv_gl00132
  - use_case_id_gmv_gl00138
  - use_case_id_gmv_gl00091
  - use_case_id_gmv_gl00083
  - use_case_id_hoh_sp00013
  - use_case_id_gmv_gl00206
  - use_case_id_gmv_gl00320
  - use_case_id_gmv_gl00022
  - use_case_id_gmv_gl00327
  - use_case_id_gmv_gl00268
  - use_case_id_gmv_gl00068
  - use_case_id_mag_sp00009
  - use_case_id_jac_sp00001
  - use_case_id_gmv_gl00200
  - use_case_id_gmv_gl00301
  - use_case_id_gmv_gl00238
  - use_case_id_gmv_gl00336
  - use_case_id_gmv_gl00338
  - use_case_id_gmv_gl00113
  - use_case_id_gmv_gl00309
  - use_case_id_gmv_gl00216
  - use_case_id_gmv_gl00349
  - use_case_id_gmv_gl00388
  - use_case_id_kri_gl00061
  - use_case_id_kri_gl00060
  - use_case_id_gmv_gl00217
  - use_case_id_gmv_gl00367
  - use_case_id_gmv_gl00284
  - use_case_id_gmv_gl00328
  - use_case_id_gmv_gl00237
  - use_case_id_gmv_gl00227
  - use_case_id_gmv_gl00240
  - use_case_id_gmv_gl00134
  - use_case_id_gmv_gl00023
  - use_case_id_gmv_gl00299
  - use_case_id_gmv_gl00361
  - use_case_id_gmv_gl00239
  - use_case_id_cia_sp00012
  - use_case_id_ken_sp00001
  - use_case_id_gmv_gl00412
  - use_case_id_gmv_gl00420
  - use_case_id_gmv_gl00341
  - use_case_id_gmv_gl00235
  - use_case_id_gmv_gl00333
  - use_case_id_gmv_gl00234
  - use_case_id_hoh_sp00019
  - use_case_id_jac_gl00269
  - use_case_id_gmv_gl00330
  - use_case_id_gmv_gl00313
  - use_case_id_gmv_gl00415
  - use_case_id_gmv_gl00121
  - use_case_id_gmv_gl00236
  - use_case_id_gmv_gl00228
  - use_case_id_gmv_gl00095
  - use_case_id_gmv_gl00424
  - use_case_id_gmv_gl00263
  - use_case_id_gmv_gl00241
  - use_case_id_gmv_gl00355
  - use_case_id_gmv_gl00352
  - use_case_id_gmv_gl00056
  - use_case_id_gmv_gl00034
  - use_case_id_gal_sp00001
  - use_case_id_gmv_gl00300
  - use_case_id_hof_sp00003
  - use_case_id_gmv_gl00394
  - use_case_id_gmv_gl00312
  - use_case_id_gmv_gl00161
  - use_case_id_gmv_gl00162
  - use_case_id_gmv_gl00344
  - use_case_id_wen_sp00003
  - use_case_id_gmv_gl00293
  - use_case_id_gmv_gl00295
  - use_case_id_gmv_gl00049
  - use_case_id_uya_sp00017
  - use_case_id_cia_sp00015
  - use_case_id_gmv_gl00050
  - use_case_id_gmv_gl00491
  - use_case_id_gmv_gl00417
  - use_case_id_mag_sp00004
  - use_case_id_gmv_gl00370
  - use_case_id_gmv_gl00215
  - use_case_id_gmv_gl00489
  - use_case_id_gmv_gl00457
  - use_case_id_gmv_gl00365
  - use_case_id_cia_sp00011
  - use_case_id_gmv_gl00472
  - use_case_id_gmv_gl00233
  - use_case_id_gmv_gl00231
  - use_case_id_wen_sp00004
  - use_case_id_gmv_gl00499
  - use_case_id_gmv_gl00387
  - use_case_id_gmv_gl00052
  - use_case_id_gmv_gl00329
  - use_case_id_gmv_gl00443
  - use_case_id_gmv_gl00474
  - use_case_id_cra_sp00014
  - use_case_id_gmv_gl00292
  - use_case_id_gmv_gl00410
  - use_case_id_gmv_gl00275
  - use_case_id_gmv_gl00189
  - use_case_id_wen_sp00005
  - use_case_id_gmv_gl00150
  - use_case_id_gmv_gl00363
  - use_case_id_gmv_gl00369
  - use_case_id_wen_sp00006
  - use_case_id_gmv_gl00471
  - use_case_id_gmv_gl00442
  - use_case_id_gmv_gl00445
  - use_case_id_gmv_gl00444
  - use_case_id_gmv_gl00347
  - use_case_id_gmv_gl00426
  - use_case_id_gmv_gl00283
  - use_case_id_gmv_gl00448
  - use_case_id_gmv_gl00492
  - use_case_id_hoh_sp00005
  - use_case_id_gmv_gl00354
  - use_case_id_wen_sp00007
  - use_case_id_gmv_gl00470
  - use_case_id_gmv_gl00520
  - use_case_id_cia_sp00016
  - use_case_id_gmv_gl00509
  - use_case_id_gmv_gl00497
  - use_case_id_gmv_gl00414
  - use_case_id_uya_gl00473
  - use_case_id_gmv_gl00429
  - use_case_id_gmv_gl00506
  - use_case_id_gmv_gl00139
  - use_case_id_gmv_gl00505
  - use_case_id_gmv_gl00495
  - use_case_id_gmv_gl00166
  - use_case_id_gmv_gl00462
  - use_case_id_gmv_gl00440
  - use_case_id_gmv_gl00441
  - use_case_id_gmv_gl00428
  - use_case_id_gmv_gl00427
  - use_case_id_gmv_gl00433
  - use_case_id_gmv_gl00432
  - use_case_id_hof_sp00025
  - use_case_id_pre_gl00439
  - use_case_id_gmv_gl00425
  - use_case_id_gmv_gl00316
  - use_case_id_gmv_gl00494
  - use_case_id_gmv_gl00532
  - use_case_id_gmv_gl00496
  - use_case_id_gmv_gl00464
  - use_case_id_gmv_gl00463
  - use_case_id_gmv_gl00531
  - use_case_id_gmv_gl00438
  - use_case_id_gal_sp00003
  - use_case_id_gmv_gl00493
  - use_case_id_gmv_gl00484
  - use_case_id_gmv_gl00498
  purely_categorical_feats:
  - proyecto
  - severidad
  - srccountry
  - dstcountry
  - user_str
  - protocol_str
  - status_str
  - use_case_id
  subversion: 20250115-130743
  text_enc:
  - CNNmulti512
  - SWIVEL20
  verbose: true
