deps:
  model:
    encoder_path: models/uc3m_model/encoding
    model_path: models/uc3m_model
outs:
  env_path_name: output_path
  output_folder: inference
params:
  binary_feats:
  - schedule_L1
  - srcip_exists
  - dstip_exists
  - srcip_public
  - dstip_public
  binary_type: PlusMinusOne
  bincat_dict:
    schedule_L1: 24x7
  nlp_feats:
  - - titulo_investigacion
    - use_case_name
    - url_str
    - id_str
  - - extra_data_str
    - action_str
    - fuente
  - - alert_name
  numeric_feats:
  - AlertLevel
  - numero_eventos
  ohe_feats:
  - proyecto_hicks
  - proyecto_kennedy
  - proyecto_magenta
  - proyecto_bali
  - proyecto_cian
  - proyecto_hohens
  - proyecto_jacoblemaire
  - proyecto_wendycalvin
  - proyecto_hoffmann
  - proyecto_galeotti
  - proyecto_harish
  - proyecto_crabeels
  - proyecto_kring
  - proyecto_magenta_publico
  - proyecto_pecs
  - proyecto_masami
  - proyecto_astropolis
  - proyecto_presque
  - proyecto_potomac
  - proyecto_s12mp-opmaev
  - severidad_medium
  - severidad_critical
  - severidad_high
  - srccountry_
  - srccountry_kenya
  - srccountry_united states
  - srccountry_austria
  - srccountry_germany
  - srccountry_portugal
  - srccountry_egypt
  - srccountry_sweden
  - srccountry_turkey
  - srccountry_india
  - srccountry_oman
  - srccountry_mexico
  - srccountry_guatemala
  - srccountry_hong kong
  - srccountry_spain
  - srccountry_france
  - srccountry_netherlands
  - srccountry_ireland
  - srccountry_algeria
  - srccountry_canada
  - srccountry_poland
  - srccountry_japan
  - srccountry_united kingdom
  - srccountry_romania
  - srccountry_singapore
  - srccountry_brazil
  - srccountry_south africa
  - srccountry_moldova, republic of
  - srccountry_china
  - srccountry_taiwan
  - srccountry_indonesia
  - srccountry_australia
  - srccountry_malaysia
  - srccountry_korea
  - srccountry_thailand
  - srccountry_luxembourg
  - srccountry_belgium
  - srccountry_latvia
  - srccountry_denmark
  - srccountry_cambodia
  - srccountry_argentina
  - srccountry_switzerland
  - srccountry_bulgaria
  - srccountry_finland
  - srccountry_russian federation
  - srccountry_bahrain
  - srccountry_greece
  - srccountry_italy
  - srccountry_lithuania
  - srccountry_mauritania
  - srccountry_morocco
  - srccountry_vietnam
  - srccountry_albania
  - srccountry_czech republic
  - dstcountry_
  - dstcountry_spain
  - dstcountry_united states
  - dstcountry_india
  - dstcountry_poland
  - dstcountry_singapore
  - dstcountry_bosnia and herzegovina
  - dstcountry_germany
  - dstcountry_france
  - dstcountry_ireland
  - dstcountry_portugal
  - dstcountry_russian federation
  - dstcountry_ukraine
  - dstcountry_turkey
  - dstcountry_japan
  - dstcountry_netherlands
  - dstcountry_canada
  - dstcountry_sweden
  - dstcountry_hong kong
  - dstcountry_united kingdom
  - dstcountry_argentina
  - dstcountry_china
  - dstcountry_denmark
  - dstcountry_czech republic
  - dstcountry_norway
  - dstcountry_bulgaria
  - dstcountry_finland
  - dstcountry_iceland
  - dstcountry_australia
  - dstcountry_brazil
  - dstcountry_philippines
  - dstcountry_belgium
  - dstcountry_korea
  - dstcountry_lithuania
  - dstcountry_slovakia
  - dstcountry_austria
  - dstcountry_mexico
  - dstcountry_taiwan
  - dstcountry_chile
  - dstcountry_hungary
  - dstcountry_italy
  - dstcountry_malaysia
  - dstcountry_senegal
  - dstcountry_romania
  - dstcountry_colombia
  - dstcountry_luxembourg
  - user_str_
  - user_str_root
  - user_str_admin
  - user_str_guest
  - user_str_default
  - user_str_support
  - user_str_user
  - protocol_str_
  - protocol_str_tcp
  - protocol_str_http
  - protocol_str_udp
  - protocol_str_icmp
  - protocol_str_get
  - protocol_str_head
  - protocol_str_poll
  - protocol_str_patch
  - protocol_str_pfsync
  - protocol_str_proppatch
  - protocol_str_testzzz
  - protocol_str_x-ms-enumatts
  - protocol_str_rpc_out_data
  - protocol_str_search
  - protocol_str_orderpatch
  - protocol_str_acl
  - status_str_
  - status_str_secret - heartbeatfailure
  - status_str_unsafe
  - status_str_defense
  - status_str_vulnerability
  - status_str_quarantined
  - status_str_url
  - status_str_malware
  - status_str_system log
  - status_str_execution
  - status_str_cleared
  - status_str_discovery
  - status_str_role - assignuserorgroup
  - status_str_user - addedtogroup
  - status_str_lateral
  - status_str_abnormal
  - status_str_command
  - status_str_privilege
  - status_str_spyware
  - status_str_initial
  - status_str_wildfire
  - status_str_scan
  - status_str_virus
  - status_str_user - lockout
  - status_str_impact
  - status_str_persistence
  - status_str_user - loginfailure
  - status_str_unscored
  - status_str_credential
  - status_str_exploit
  - status_str_file
  purely_categorical_feats:
  - proyecto
  - severidad
  - srccountry
  - dstcountry
  - user_str
  - protocol_str
  - status_str
  subversion: 20250122-122430
  text_enc:
  - CNNmulti512
  - SWIVEL20
  verbose: true
